---
title: "Market Survey Statistics - `r format(Sys.Date(), '%B %Y')` Highlights"
output: 
  word_document:
    reference_docx: styles_reference.docx
---

```{r setup, include=FALSE}
# Set echo=FALSE as default for code cells
knitr::opts_chunk$set(echo=FALSE)

# Load the required libraries
library(knitr) # Creating documents
library(flextable) # Nicely formatted tables
library(rworldmap) # World map
library(ggplot2) # Creating plots
library(RSQLite)

# Set the table formatting defaults
set_flextable_defaults(font.family="Times New Roman", font.size=5, font.color="black",
                       text.align="left", table.layout="fixed", theme_fun="theme_booktabs")
```

## M1-Form Data Processing and Analysis

```{r M1 Survey Processing, eval=FALSE}

repository <- file.path(dirname(rstudioapi::getSourceEditorContext()$path), "..", "..")
setwd(repository) # Required for file.choose() function

getwd()

# Load the general R functions
#source(file.path(repository, "functions.R"))

# Note the secure data path
secureDataFolder <- file.path(repository, "data", "secure")

# Note the open data path
openDataFolder <- file.path(repository, "data", "open")

# Some general ggplot settings
plotTextSize <- 9
xAxisText <- list(
  "angle" = 35,
  "size" = plotTextSize,
  "vjust" = 1.1,
  "hjust" = 1
)

```

```{r NSDP table}
x <- 57

# Create the NSDP table
nsdpIndicators <- data.frame(
  "Policy Objectives"=c("ENV 1.3: Reduce reliance on food imports through import substitution for food products that can be produced domestically"),
"SMART Indicators"=c("ENV 1.3.1 (proxy) Total value per kilo of Staples, Vegetables and Fruits from Port Vila Central Market)"),
                       
  "Indicator Value"= c(
    x),check.names=FALSE, stringsAsFactors=FALSE)


indicatorsTable <- flextable(nsdpIndicators)

# Add a header row and set background colour
indicatorsTable <- bg(indicatorsTable, bg="coral1", part="header")

# Set the vertical alignment to top
indicatorsTable <- valign(indicatorsTable, valign="top", part="all")

# Merge repeated values in the Policy Objectives column
indicatorsTable <- merge_v(indicatorsTable, j = "Policy Objectives")

# Set table width to 100%
indicatorsTable <- set_table_properties(indicatorsTable, width=1, layout="autofit")

# Set the theme
indicatorsTable <- theme_booktabs(indicatorsTable)

# Print table
indicatorsTable
```



```
