---
title: "Market Survey Statistics - `r format(Sys.Date(), '%B %Y')` Highlights"
output:
  word_document:
    reference_docx: styles_reference.docx
always_allow_html: yes
---

```{r setup, include=FALSE}
# Set echo=FALSE as default for code cells
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      dpi = 600)

```

```{r preparation, include = FALSE}
# Load the required libraries
library(knitr) # Creating documents
#install.packages("flextable")
library(flextable) # Nicely formatted tables
library(rnaturalearth) # World map
library(sf) # Working with spatial data
library(ggplot2) # Creating plots
library(dplyr) # Working with data
library(tidyr) # For pivoting data.frames
library(janitor) # Adding row and column totals
library(RSQLite)
library(plotly)

setwd(paste0(getwd()))
getwd()

#Establish connection the the SQLite database
mydb <- dbConnect(RSQLite::SQLite(), "../../data/secure/sqlite/ms.sqlite")



# Some general ggplot settings
plotTextSize <- 9
xAxisText <- list(
  "angle" = 35,
  "size" = plotTextSize,
  "vjust" = 1.1,
  "hjust" = 1
)
                       
```

## M1-Form Data Processing and Analysis

```{r M1 Survey Processing, eval=FALSE}





```


```{r NSDP_table}
x<- 57

# Create the NSDP table
nsdpIndicators <- data.frame(
  "Policy Objectives"=c("ENV 1.3: Reduce reliance on food imports through import substitution for food products that can be produced domestically"),
"SMART Indicators"=c("ENV 1.3.1 (proxy) Total value per kilo of Staples, Vegetables and Fruits from Port Vila Central Market)"),
                       
  "Indicator Value"= c(
    x),check.names=FALSE, stringsAsFactors=FALSE)


# Round the indicator values
#nsdpIndicators$`Indicator Value` <- round(nsdpIndicators$`Indicator Value`, digits = 2)

# Initiailise a flextable object for NSDP table
indicatorsTable <- flextable(nsdpIndicators)

# Add a header row and set background colour
indicatorsTable <- bg(indicatorsTable, bg="coral1", part="header")

# Set the vertical alignment to top
indicatorsTable <- valign(indicatorsTable, valign="top", part="all")

# Merge repeated values in the Policy Objectives column
indicatorsTable <- merge_v(indicatorsTable, j = "Policy Objectives")

# Set table width to 100%
indicatorsTable <- set_table_properties(indicatorsTable, width=1, layout="autofit")

# Set the theme
indicatorsTable <- theme_booktabs(indicatorsTable)

# Print table
indicatorsTable
```

```{r Staple_food_trends}

#Staple Food Trend comparisons
histQtySupplied_staple <- dbGetQuery(mydb, "SELECT (Year||'-'||Quarter) AS myquarter, 
                                            Category, 
                                            Major, 
                                            ROUND(SUM(Totalweight_kg)) AS totalWeight
                                     FROM QuantitySupplied_W
                                     WHERE category = 'Staple'
                                     GROUP BY myquarter, Category, Major
                              ")

staple_history <- histQtySupplied_staple %>%
  pivot_wider(names_from = Major, values_from = totalWeight)

staple_history %>%
  plot_ly(x = ~myquarter,
          y = ~Banana_green,
          color = "blue",
          type = "scatter",
          mode = "lines+markers",
          name = "Green Banana",
          line = list(width = 3)) %>%
  
  add_trace(x = ~myquarter,
            y = ~FijiTaro,
            color = "red",
            name = "Fiji Taro") %>%
  
  add_trace(x = ~myquarter,
            y = ~IslandTaro,
            color = "green",
            name = "Island Taro") %>%
  
  add_trace(x = ~myquarter,
            y = ~Manioc,
            color = "yellow",
            name = "Manioc") %>%
  
  add_trace(x = ~myquarter,
            y = ~Dried_coconuts,
            color = "orange",
            name = "Dried Coconut") %>%
  
  add_trace(x = ~myquarter,
            y = ~Yams,
            color = "violet",
            name = "Yam") %>%
  
  add_trace(x = ~myquarter,
            y = ~SweetPotato_kumala,
            color = "indigo",
            name = "Sweet Potato (Kumala)") %>%  
  
  plotly::layout(xaxis = list(title = "Quarter"), yaxis = list(title = 'Value (Kilogram))'))


```





